import "./globals.css";
import { Arvo } from "next/font/google";
import Nav from "./nav/Nav";
import RecoilContainer from "./components/RecoilContainer";
import LoginModal from "./components/modal/LoginModal";
import getCurrentUser from "./actions/getCurrentUser";
import RegisterModal from "./components/modal/RegisterModal";
import AddItemModal from "./components/modal/AddItemModal";
import PageWapper from "./components/PageWapper";
import MyLoading from "./MyLoading";

const font = Arvo({
  weight: "400",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={`${font.className} overflow-hidden`}>
        <RecoilContainer>
          <MyLoading>
            <AddItemModal />
            <LoginModal />
            <RegisterModal />
            <Nav currentUser={currentUser} />
            <div className="overflow-x-hidden max-h-screen">
              <PageWapper>{children}</PageWapper>
              {/* {children} */}
            </div>
          </MyLoading>
        </RecoilContainer>
      </body>
    </html>
  );
}
